contact_links:
  - name: Add a missing Textpattern plugin
    url: https://github.com/textpattern/textpattern-curated-plugins-list/issues/new?labels=plugin-add&template=add-a-missing-textpattern-plugin.md&title=%5BADD%5D+xxxxx
    about: Use this form to suggest a Textpattern plugin to be added to the plugins website.
  - name: Report a broken Textpattern plugin listing
    url: https://github.com/textpattern/textpattern-curated-plugins-list/issues/new?labels=plugin-broken&template=report-a-broken-textpattern-plugin-listing.md&title=%5BBROKEN%5D+xxxxx
    about: Use this form to report a broken Textpattern plugin listed on the plugins website.
